const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@Baaba Devs";
const email = "Email";
const emailHint = "Enter mail";
const password = "Password";
const passwordHint = "*******";
const forgetPass = "Forget Password";
const login = "Log in";
const signup = "Sign up";
const reTypepassword = "Retype Password";
const name = "Name";
const nameHint = "Enter Name";
const createNewAccount = "or, create a New Account";
const loginwith = "Log in with";
const privacyPolicy = "Privacy Policy";
const terms = "Terms and Conditions";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
